"""Static grids must never leak between assemblies or be generated by analysis."""
import copy
import hashlib
import json
from pathlib import Path

import pandas as pd
import pytest

import spice
from spice import data_loaders as dl


def write_reference(root, assembly):
    spice.config['params']['assembly']=assembly
    lengths=dl.load_chrom_lengths()
    folder=root/assembly;folder.mkdir(parents=True)
    table=pd.DataFrame({'chrom':lengths.index,'start':0,'end':lengths.values-1})
    path=folder/'segmentation_4000.tsv';table.to_csv(path,sep='\t',index=False)
    manifest=dict(schema=1,assembly=assembly,coordinate_system='0-based inclusive',
        chromosome_lengths={c:int(n) for c,n in lengths.items()},
        files={path.name:dict(bin_size=4000,bins=len(table),sha256=hashlib.sha256(path.read_bytes()).hexdigest())})
    (folder/'manifest.json').write_text(json.dumps(manifest))
    return path


@pytest.fixture
def reference(tmp_path,monkeypatch):
    cfg=copy.deepcopy(spice.config)
    cfg['input_files']['segmentations']=str(tmp_path/'grids')
    cfg.setdefault('directories',{})['base_dir']=str(tmp_path)
    monkeypatch.setattr(spice,'config',cfg)
    for assembly in ['hg19','hg38']: write_reference(tmp_path/'grids',assembly)
    cfg['params']['assembly']='hg19'
    dl._read_segmentation_reference.cache_clear()
    return tmp_path


def test_live_assembly_selects_distinct_read_only_grids(reference):
    hg19=dl.load_segmentation(4000)
    spice.config['params']['assembly']='hg38'
    hg38=dl.load_segmentation(4000)
    assert hg19.loc['chr1'].index.get_level_values('end').max()==249250620
    assert hg38.loc['chr1'].index.get_level_values('end').max()==248956421
    assert not (reference/'results').exists()


def test_cache_reuses_parsing_but_not_caller_mutations(reference):
    first=dl.load_segmentation(4000)
    first['changed']=True
    second=dl.load_segmentation(4000)
    assert list(second.columns)==[]
    assert dl._read_segmentation_reference.cache_info().hits==1


def test_missing_reference_is_error_without_creating_anything(reference):
    with pytest.raises(FileNotFoundError,match='Missing prepared segmentation'): dl.load_segmentation(20000)
    spice.config['input_files']['segmentations']=str(reference/'absent')
    with pytest.raises(FileNotFoundError): dl.load_segmentation(4000)
    assert not (reference/'absent').exists()
    spice.config['input_files']['segmentations']=None
    with pytest.raises(FileNotFoundError,match='Generate them separately'): dl.load_segmentation(4000)


def test_rejects_wrong_assembly_manifest(reference):
    p=reference/'grids/hg19/manifest.json';meta=json.loads(p.read_text());meta['assembly']='hg38';p.write_text(json.dumps(meta))
    with pytest.raises(ValueError,match='configured assembly'): dl.load_segmentation(4000)


def test_changed_cached_file_is_revalidated(reference):
    dl.load_segmentation(4000)
    p=reference/'grids/hg19/segmentation_4000.tsv'
    p.write_text(p.read_text()+'\n')
    with pytest.raises(ValueError,match='checksum'): dl.load_segmentation(4000)


def test_relative_reference_root_uses_live_base_directory(reference):
    spice.config['input_files']['segmentations']='grids'
    assert len(dl.load_segmentation(4000))==24


@pytest.mark.parametrize('size',[None,True,0,-1,4000.5])
def test_invalid_bin_sizes_fail_before_file_lookup(reference,size):
    with pytest.raises(ValueError,match='positive integer'): dl.load_segmentation(size)
