name: 'loci_example'

input_files:
  final_events: 'data/pcawg_final_events_chr1_chr2.tsv'

directories:
  base_dir: '.'

loci_detection:
  N_loci: 10
  th_locus_prominence: 1 # Needs to be this low because we do not have enough data

note: 'Example configuration for loci detection and assignment'
